---
rows: 2
cols: 2
period: 500
percentAnimalSlim: -5;
setProbablyTable:
  Wolf:
    Horse: 50
    Duck: 40
  Horse:
    Plant: 100
  Duck:
    Caterpillar: 90
    Plant: 100
  Caterpillar:
    Plant: 100
  Plant: {}

